apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: guestbook-test
          # image: gcr.io/google-samples/gb-frontend:v5
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
