apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-test
  template:
    metadata:
      labels:
        app: guestbook-test
    spec:
      containers:
        - name: guestbook-test
          # image: gcr.io/google-samples/gb-frontend:v5
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-test