apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: guestbook
          image: gcr.io/google-samples/gb-frontend:v5
